# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# LESSON: CI WORKFLOW FOR A SIMPLE WEB APP - REACT-SLINGSHOT
defaults: &defaults
  docker:
        - image: circleci/node:13.8.0

# Define a job to be invoked later in a workflow.
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
      
